name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy our silly web page
        uses: appleboy/ssh-action@v0.12
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secretes.SSH_KEY}}
          username: ${{secretes.SSH_USERNAME}}

          script: |
            cd /srv/code/
            git clone git@github.com:johnkisch/deploytest.git
            sudo systemctl reload httpd